"""empty message

Revision ID: 396785f544e1
Revises: 34e198e44378
Create Date: 2026-02-13 12:21:52.523545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396785f544e1'
down_revision = '34e198e44378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
